## Numpy array and basics
learn about numpy

In [2]:
import numpy as np

## creating array 

In [6]:
arr_1 = np.array([1,2,3,4])
print("1d array:", arr_1)

arr_2 = np.array([[1,2,3],[4,5,6]])
print("2d array", arr_2)

1d array: [1 2 3 4]
2d array [[1 2 3]
 [4 5 6]]


## list vs array 

In [12]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

py_arr = np.array ([1,2,3])
print("python array multiplication", py_arr*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


## Creating array from scratch


In [21]:
zeros = np.zeros([3,3])
print("zeros arrays:\n", zeros)

ones = np.ones([2,3])
print("one array:\n", ones)

full = np.full([2,2], 5)
print("full array:\n", full)

random = np.random.random([2,3])
print("random array:\n", random)

sequence = np.arange(0,11,1)
print("sequence array:\n", sequence)

zeros arrays:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[5 5]
 [5 5]]
random array:
 [[0.24479656 0.27585012 0.2994297 ]
 [0.84774655 0.62740344 0.35553614]]
sequence array:
 [ 0  1  2  3  4  5  6  7  8  9 10]


## Vector, Matrix, Tensor

In [26]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6], [7,8]]])
print("tesnor:", tensor)

vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
tesnor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties 

In [27]:
arr = np.array([[1,2,3],
                [2,3,4]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DataType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DataType:  int64


## Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshape array ", reshaped)

flattened = reshaped.flatten()
print("Flattened array ", flattened)

# returns view, instead of copy
raveled = reshaped.ravel()
print("Raveled array ", raveled)

transpose = reshaped.T
print("Transpose array ", transpose)





Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
